/**
 * Sample book catalogue for LPUdesk.
 * Each book stores where it is physically kept: floor -> section -> shelf.
 * Later this array can be replaced by data fetched from a real database.
 */
export const sampleBooks = [
  {
    id: 1,
    title: "Introduction to Algorithms",
    author: "Thomas H. Cormen, Charles E. Leiserson",
    category: "Computer Science",
    subject: "Algorithms & Data Structures",
    isbn: "9780262046305",
    floor: 2,
    section: "Computer Science Section",
    shelf: "C-14",
    copiesTotal: 6,
    copiesAvailable: 3,
  },
  {
    id: 2,
    title: "Operating System Concepts",
    author: "Abraham Silberschatz, Peter B. Galvin",
    category: "Computer Science",
    subject: "Operating Systems",
    isbn: "9781119800361",
    floor: 2,
    section: "Computer Science Section",
    shelf: "C-09",
    copiesTotal: 5,
    copiesAvailable: 2,
  },
  {
    id: 3,
    title: "Database System Concepts",
    author: "Abraham Silberschatz, Henry F. Korth",
    category: "Computer Science",
    subject: "Database Management Systems",
    isbn: "9780078022159",
    floor: 2,
    section: "Computer Science Section",
    shelf: "C-11",
    copiesTotal: 4,
    copiesAvailable: 0,
  },
  {
    id: 4,
    title: "Computer Networks",
    author: "Andrew S. Tanenbaum, David J. Wetherall",
    category: "Computer Science",
    subject: "Computer Networks",
    isbn: "9780132126953",
    floor: 2,
    section: "Computer Science Section",
    shelf: "C-16",
    copiesTotal: 5,
    copiesAvailable: 4,
  },
  {
    id: 5,
    title: "Clean Code: A Handbook of Agile Software Craftsmanship",
    author: "Robert C. Martin",
    category: "Computer Science",
    subject: "Software Engineering",
    isbn: "9780132350884",
    floor: 2,
    section: "Computer Science Section",
    shelf: "C-21",
    copiesTotal: 3,
    copiesAvailable: 1,
  },
  {
    id: 6,
    title: "Artificial Intelligence: A Modern Approach",
    author: "Stuart Russell, Peter Norvig",
    category: "Computer Science",
    subject: "Artificial Intelligence",
    isbn: "9780134610993",
    floor: 2,
    section: "Computer Science Section",
    shelf: "C-24",
    copiesTotal: 4,
    copiesAvailable: 2,
  },
  {
    id: 7,
    title: "Let Us C",
    author: "Yashavant Kanetkar",
    category: "Computer Science",
    subject: "C Programming",
    isbn: "9789389845000",
    floor: 2,
    section: "Programming Lab Reference Section",
    shelf: "C-03",
    copiesTotal: 10,
    copiesAvailable: 7,
  },
  {
    id: 8,
    title: "Data Structures Using C",
    author: "Reema Thareja",
    category: "Computer Science",
    subject: "Data Structures",
    isbn: "9780198099307",
    floor: 2,
    section: "Programming Lab Reference Section",
    shelf: "C-05",
    copiesTotal: 8,
    copiesAvailable: 5,
  },
  {
    id: 9,
    title: "Higher Engineering Mathematics",
    author: "B. S. Grewal",
    category: "Mathematics",
    subject: "Engineering Mathematics",
    isbn: "9788193328491",
    floor: 1,
    section: "Mathematics & Basic Sciences Section",
    shelf: "M-07",
    copiesTotal: 12,
    copiesAvailable: 6,
  },
  {
    id: 10,
    title: "Advanced Engineering Mathematics",
    author: "Erwin Kreyszig",
    category: "Mathematics",
    subject: "Applied Mathematics",
    isbn: "9780470458365",
    floor: 1,
    section: "Mathematics & Basic Sciences Section",
    shelf: "M-08",
    copiesTotal: 6,
    copiesAvailable: 2,
  },
  {
    id: 11,
    title: "Concepts of Physics (Volume 1)",
    author: "H. C. Verma",
    category: "Physics",
    subject: "Mechanics & Waves",
    isbn: "9788177091878",
    floor: 1,
    section: "Physics Section",
    shelf: "P-04",
    copiesTotal: 9,
    copiesAvailable: 4,
  },
  {
    id: 12,
    title: "Organic Chemistry",
    author: "Robert T. Morrison, Robert N. Boyd",
    category: "Chemistry",
    subject: "Organic Chemistry",
    isbn: "9789332552395",
    floor: 1,
    section: "Chemistry Section",
    shelf: "CH-02",
    copiesTotal: 5,
    copiesAvailable: 3,
  },
  {
    id: 13,
    title: "Engineering Mechanics: Statics and Dynamics",
    author: "Russell C. Hibbeler",
    category: "Mechanical Engineering",
    subject: "Engineering Mechanics",
    isbn: "9780134814971",
    floor: 3,
    section: "Mechanical Engineering Section",
    shelf: "ME-12",
    copiesTotal: 6,
    copiesAvailable: 1,
  },
  {
    id: 14,
    title: "Thermodynamics: An Engineering Approach",
    author: "Yunus A. Cengel, Michael A. Boles",
    category: "Mechanical Engineering",
    subject: "Thermodynamics",
    isbn: "9781259822674",
    floor: 3,
    section: "Mechanical Engineering Section",
    shelf: "ME-05",
    copiesTotal: 7,
    copiesAvailable: 3,
  },
  {
    id: 15,
    title: "Theory of Machines",
    author: "R. S. Khurmi, J. K. Gupta",
    category: "Mechanical Engineering",
    subject: "Kinematics of Machines",
    isbn: "9788121925242",
    floor: 3,
    section: "Mechanical Engineering Section",
    shelf: "ME-09",
    copiesTotal: 5,
    copiesAvailable: 0,
  },
  {
    id: 16,
    title: "Strength of Materials",
    author: "R. K. Bansal",
    category: "Civil Engineering",
    subject: "Solid Mechanics",
    isbn: "9789385919152",
    floor: 3,
    section: "Civil Engineering Section",
    shelf: "CE-04",
    copiesTotal: 6,
    copiesAvailable: 4,
  },
  {
    id: 17,
    title: "Surveying (Volume 1)",
    author: "B. C. Punmia, Ashok Kumar Jain",
    category: "Civil Engineering",
    subject: "Surveying & Levelling",
    isbn: "9788170088530",
    floor: 3,
    section: "Civil Engineering Section",
    shelf: "CE-08",
    copiesTotal: 4,
    copiesAvailable: 2,
  },
  {
    id: 18,
    title: "Principles of Electronics",
    author: "V. K. Mehta, Rohit Mehta",
    category: "Electronics Engineering",
    subject: "Basic Electronics",
    isbn: "9788121924506",
    floor: 3,
    section: "Electronics & Electrical Section",
    shelf: "EC-06",
    copiesTotal: 8,
    copiesAvailable: 5,
  },
  {
    id: 19,
    title: "Microelectronic Circuits",
    author: "Adel S. Sedra, Kenneth C. Smith",
    category: "Electronics Engineering",
    subject: "Analog Circuits",
    isbn: "9780199339136",
    floor: 3,
    section: "Electronics & Electrical Section",
    shelf: "EC-11",
    copiesTotal: 4,
    copiesAvailable: 1,
  },
  {
    id: 20,
    title: "Principles of Management",
    author: "Harold Koontz, Heinz Weihrich",
    category: "Management",
    subject: "Management Principles",
    isbn: "9789339222864",
    floor: 4,
    section: "Management & Commerce Section",
    shelf: "MG-03",
    copiesTotal: 7,
    copiesAvailable: 4,
  },
  {
    id: 21,
    title: "Marketing Management",
    author: "Philip Kotler, Kevin Lane Keller",
    category: "Management",
    subject: "Marketing",
    isbn: "9789332557185",
    floor: 4,
    section: "Management & Commerce Section",
    shelf: "MG-05",
    copiesTotal: 5,
    copiesAvailable: 2,
  },
  {
    id: 22,
    title: "Financial Management: Theory and Practice",
    author: "I. M. Pandey",
    category: "Management",
    subject: "Finance & Accounting",
    isbn: "9789325982291",
    floor: 4,
    section: "Management & Commerce Section",
    shelf: "MG-09",
    copiesTotal: 6,
    copiesAvailable: 3,
  },
  {
    id: 23,
    title: "Constitution of India",
    author: "P. M. Bakshi",
    category: "Law",
    subject: "Constitutional Law",
    isbn: "9789389176728",
    floor: 4,
    section: "Law & Legal Studies Section",
    shelf: "LW-03",
    copiesTotal: 5,
    copiesAvailable: 3,
  },
  {
    id: 24,
    title: "Principles of Agronomy",
    author: "S. R. Reddy",
    category: "Agriculture",
    subject: "Agronomy",
    isbn: "9789387590861",
    floor: 4,
    section: "Agriculture Science Section",
    shelf: "AG-02",
    copiesTotal: 4,
    copiesAvailable: 2,
  },
  {
    id: 25,
    title: "Indian Polity",
    author: "M. Laxmikanth",
    category: "Competitive Exams",
    subject: "General Studies",
    isbn: "9789390961399",
    floor: 0,
    section: "Competitive Exams & GK Section",
    shelf: "GK-03",
    copiesTotal: 10,
    copiesAvailable: 6,
  },
  {
    id: 26,
    title: "High School English Grammar & Composition",
    author: "Wren & Martin",
    category: "Language & Communication",
    subject: "English Grammar",
    isbn: "9789352530082",
    floor: 0,
    section: "Language & Communication Section",
    shelf: "LC-04",
    copiesTotal: 8,
    copiesAvailable: 5,
  },
  {
    id: 27,
    title: "Wings of Fire: An Autobiography",
    author: "A. P. J. Abdul Kalam, Arun Tiwari",
    category: "Biography",
    subject: "Indian Biography",
    isbn: "9788173711466",
    floor: 0,
    section: "General Reading & Fiction Section",
    shelf: "GR-02",
    copiesTotal: 6,
    copiesAvailable: 4,
  },
  {
    id: 28,
    title: "The Alchemist",
    author: "Paulo Coelho",
    category: "Fiction",
    subject: "Inspirational Fiction",
    isbn: "9780062315007",
    floor: 0,
    section: "General Reading & Fiction Section",
    shelf: "GR-05",
    copiesTotal: 7,
    copiesAvailable: 0,
  },
];
